### ISSUE TITLE
Loading multi-disk bundler XML files doesn't work

### ISSUE THREAD

**Issue by RetroEdit** [alyosha-tas/GBAHawk#29]
Probably just something not implemented yet, but I can provide more details if necessary. Whenever you create a configuration with the multi-disk bundler, it will save an XML file, but these don't seem to load properly when clicking on the entry in `File > Recent ROM` list.

One exception raised was the following:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at BizHawk.Emulation.Cores.Nintendo.GBALink.GBAHawkLink.StoreSaveRam(Byte[] data)
   at BizHawk.Client.GBAHawk.MainForm.LoadSaveRam()
   at BizHawk.Client.GBAHawk.MainForm.LoadRomInternal(String path, LoadRomArgs args, Boolean& failureIsFromAskSave)
   at BizHawk.Client.GBAHawk.MainForm.LoadRom(String path, LoadRomArgs args, Boolean& failureIsFromAskSave)
   at BizHawk.Client.GBAHawk.MainForm.LoadRom(String path, LoadRomArgs args)
```

**Comment by alyosha-tas** [comment]
Fixed in master thanks for the report
