### ISSUE TITLE
AVI Writer Autocloses The Window

### ISSUE THREAD

**Issue by GoddessMaria15** [alyosha-tas/GBAHawk#39]
not sure if it was already mentioned, but whenever i attempt to record an AVI, the emulator would crash for 2 seconds before automatically closes itself. at first, i thought it was something up with the the config so i extracted it again as a clean folder and tried again... same result. then i tried a few previous versions and the same thing happened. updated codecs and Windows... nope.

is this something intentional?

**Comment by alyosha-tas** [comment]
I tried just now with both AVI writer and the ffmpeg version and both work for me. What specific settings are you using?

**Comment by GoddessMaria15** [comment]
aside from the hotkeys and bios, nothing particular.

if this helps, here;s the log from the Event Viewer:

Log Name:      Application
Source:        .NET Runtime
Date:          8/26/2024 9:09:33 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-EUAIJIL
Description:
Application: EmuHawk.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 000000007F8411C9
Stack:
   at BizHawk.Common.AVIWriterImports.AVISaveOptions(IntPtr, Int32, Int32, Void*, Void*)
   at BizHawk.Common.AVIWriterImports.AVISaveOptions(IntPtr, Int32, Int32, Void*, Void*)
   at BizHawk.Client.EmuHawk.AviWriter+AviWriterSegment.AVISaveOptions(IntPtr, AVICOMPRESSOPTIONS ByRef, IntPtr)
   at BizHawk.Client.EmuHawk.AviWriter+AviWriterSegment.AcquireVideoCodecToken(IntPtr, CodecToken)
   at BizHawk.Client.EmuHawk.AviWriter.AcquireVideoCodecToken(System.Windows.Forms.IWin32Window)
   at BizHawk.Client.EmuHawk.MainForm.RecordAvBase(System.String, System.String, Boolean)
   at BizHawk.Client.EmuHawk.MainForm.RecordAVMenuItem_Click(System.Object, System.EventArgs)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(System.Object, System.EventArgs)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(System.EventArgs)
   at System.Windows.Forms.ToolStripItem.HandleClick(System.EventArgs)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(System.Windows.Forms.MouseEventArgs)
   at System.Windows.Forms.ToolStrip.OnMouseUp(System.Windows.Forms.MouseEventArgs)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(System.Windows.Forms.MouseEventArgs)
   at System.Windows.Forms.Control.WmMouseUp(System.Windows.Forms.Message ByRef, System.Windows.Forms.MouseButtons, Int32)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ToolStrip.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ToolStripDropDown.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at BizHawk.Client.EmuHawk.MainForm.CheckMessages()
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(System.String[])
   at BizHawk.Client.EmuHawk.Program.Main(System.String[])

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-08-27T01:09:33.1648194Z" />
    <EventRecordID>52913</EventRecordID>
    <Correlation />
    <Execution ProcessID="18672" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-EUAIJIL</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: EmuHawk.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 000000007F8411C9
Stack:
   at BizHawk.Common.AVIWriterImports.AVISaveOptions(IntPtr, Int32, Int32, Void*, Void*)
   at BizHawk.Common.AVIWriterImports.AVISaveOptions(IntPtr, Int32, Int32, Void*, Void*)
   at BizHawk.Client.EmuHawk.AviWriter+AviWriterSegment.AVISaveOptions(IntPtr, AVICOMPRESSOPTIONS ByRef, IntPtr)
   at BizHawk.Client.EmuHawk.AviWriter+AviWriterSegment.AcquireVideoCodecToken(IntPtr, CodecToken)
   at BizHawk.Client.EmuHawk.AviWriter.AcquireVideoCodecToken(System.Windows.Forms.IWin32Window)
   at BizHawk.Client.EmuHawk.MainForm.RecordAvBase(System.String, System.String, Boolean)
   at BizHawk.Client.EmuHawk.MainForm.RecordAVMenuItem_Click(System.Object, System.EventArgs)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(System.Object, System.EventArgs)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(System.EventArgs)
   at System.Windows.Forms.ToolStripItem.HandleClick(System.EventArgs)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(System.Windows.Forms.MouseEventArgs)
   at System.Windows.Forms.ToolStrip.OnMouseUp(System.Windows.Forms.MouseEventArgs)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(System.Windows.Forms.MouseEventArgs)
   at System.Windows.Forms.Control.WmMouseUp(System.Windows.Forms.Message ByRef, System.Windows.Forms.MouseButtons, Int32)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ToolStrip.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ToolStripDropDown.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at BizHawk.Client.EmuHawk.MainForm.CheckMessages()
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(System.String[])
   at BizHawk.Client.EmuHawk.Program.Main(System.String[])
</Data>
  </EventData>
</Event>

**Comment by alyosha-tas** [comment]
What version are you using? It should be saying BizHawk.Client.GBAHawk not BizHawk.Client.EmuHawk if you are using any recent version.

**Comment by GoddessMaria15** [comment]
Oh, crap! I copied the wrong one! 

Log Name:      Application
Source:        .NET Runtime
Date:          8/18/2024 1:19:16 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-EUAIJIL
Description:
Application: GBAHawk.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at BizHawk.Common.AVIWriterImports.AVISaveOptions(IntPtr, Int32, Int32, Void*, Void*)
   at BizHawk.Client.GBAHawk.AviWriter+AviWriterSegment.AVISaveOptions(IntPtr, AVICOMPRESSOPTIONS ByRef, IntPtr)
   at BizHawk.Client.GBAHawk.AviWriter+AviWriterSegment.AcquireVideoCodecToken(IntPtr, CodecToken)
   at BizHawk.Client.GBAHawk.AviWriter.AcquireVideoCodecToken(BizHawk.Client.Common.Config)
   at BizHawk.Client.GBAHawk.MainForm.RecordAvBase(System.String, System.String, Boolean)
   at BizHawk.Client.GBAHawk.MainForm.ConfigAndRecordAVMenuItem_Click(System.Object, System.EventArgs)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(System.Object, System.EventArgs)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(System.EventArgs)
   at System.Windows.Forms.ToolStripItem.HandleClick(System.EventArgs)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(System.Windows.Forms.MouseEventArgs)
   at System.Windows.Forms.ToolStrip.OnMouseUp(System.Windows.Forms.MouseEventArgs)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(System.Windows.Forms.MouseEventArgs)
   at System.Windows.Forms.Control.WmMouseUp(System.Windows.Forms.Message ByRef, System.Windows.Forms.MouseButtons, Int32)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ToolStrip.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ToolStripDropDown.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at BizHawk.Client.GBAHawk.MainForm.CheckMessages()
   at BizHawk.Client.GBAHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.GBAHawk.Program.SubMain(System.String[])
   at BizHawk.Client.GBAHawk.Program.Main(System.String[])


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-08-18T17:19:16.7653199Z" />
    <EventRecordID>52104</EventRecordID>
    <Correlation />
    <Execution ProcessID="18800" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-EUAIJIL</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: GBAHawk.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at BizHawk.Common.AVIWriterImports.AVISaveOptions(IntPtr, Int32, Int32, Void*, Void*)
   at BizHawk.Client.GBAHawk.AviWriter+AviWriterSegment.AVISaveOptions(IntPtr, AVICOMPRESSOPTIONS ByRef, IntPtr)
   at BizHawk.Client.GBAHawk.AviWriter+AviWriterSegment.AcquireVideoCodecToken(IntPtr, CodecToken)
   at BizHawk.Client.GBAHawk.AviWriter.AcquireVideoCodecToken(BizHawk.Client.Common.Config)
   at BizHawk.Client.GBAHawk.MainForm.RecordAvBase(System.String, System.String, Boolean)
   at BizHawk.Client.GBAHawk.MainForm.ConfigAndRecordAVMenuItem_Click(System.Object, System.EventArgs)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(System.Object, System.EventArgs)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(System.EventArgs)
   at System.Windows.Forms.ToolStripItem.HandleClick(System.EventArgs)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(System.Windows.Forms.MouseEventArgs)
   at System.Windows.Forms.ToolStrip.OnMouseUp(System.Windows.Forms.MouseEventArgs)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(System.Windows.Forms.MouseEventArgs)
   at System.Windows.Forms.Control.WmMouseUp(System.Windows.Forms.Message ByRef, System.Windows.Forms.MouseButtons, Int32)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ToolStrip.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ToolStripDropDown.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at BizHawk.Client.GBAHawk.MainForm.CheckMessages()
   at BizHawk.Client.GBAHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.GBAHawk.Program.SubMain(System.String[])
   at BizHawk.Client.GBAHawk.Program.Main(System.String[])

</Data>
  </EventData>
</Event>

It still happens and the version i used was v2.1.3.

**Comment by alyosha-tas** [comment]
well based on the first error log it looks like it happens with BizHawk as well? If that is the case I would suspect a computer issue. I can only guess at the solution, but you can try:

- try ffmpeg and see if you get the same error.
- make sure 'avifil32.dll' exists on your system and has user permissions to read and execute
- running as administrator
- saving somewhere else
- run the pre-req installer again: https://github.com/TASEmulators/BizHawk-Prereqs/releases

**Comment by GoddessMaria15** [comment]
okay, i just tried the FFmpeg writer and that worked. it's weird that using the AVI writer hangs before crashing while FFmpeg writer. i even tried all of those suggestions and AVI writer still crashed. ah well.

thanks for taking the time to help, either way!

**Comment by alyosha-tas** [comment]
Huh, that is weird, but I don't think there is anything to do on my end, so I'll close this one. 

Post back if you find a solution though.
