### ISSUE TITLE
Windows 7: Shader compile error on startup

### ISSUE THREAD

**Issue by halian** [alyosha-tas/GBAHawk#50]
When I open GBAHawk 2.2.0 under Windows 7, it throws the following error, and then proceeds to open anyway. It plays just fine with the display method set to GDI+ or OpenGL.

```
System.Exception: Initialization of Display Method failed; falling back to GDI+ ---> System.InvalidOperationException: Error compiling shader:  ---> SlimDX.CompilationException ---> SlimDX.Direct3D9.Direct3D9Exception: E_FAIL: An undetermined error occurred (-2147467259)
   at SlimDX.Result.Throw[T](Object dataKey, Object dataValue)
   at SlimDX.Result.Record[T](Int32 hr, Boolean failed, Object dataKey, Object dataValue)
   at SlimDX.Result.Record[T](Int32 hr, Object dataKey, Object dataValue)
   at SlimDX.CompilationException.Check[T](Int32 hr, String errors)
   --- End of inner exception stack trace ---
   at SlimDX.Direct3D9.ShaderBytecode.Compile(Byte[] sourceData, Macro[] defines, Include includeFile, String functionName, String profile, ShaderFlags flags, String& errors)
   at BizHawk.Bizware.DirectX.IGL_SlimDX9.CreateFragmentShader(String source, String entry, Boolean required)
   --- End of inner exception stack trace ---
   at BizHawk.Bizware.DirectX.IGL_SlimDX9.CreateFragmentShader(String source, String entry, Boolean required)
   at BizHawk.Bizware.OpenTK3.GuiRenderer..ctor(IGL owner)
   at BizHawk.Client.GBAHawk.IGLExtensions.CreateRenderer(IGL gl)
   at BizHawk.Client.GBAHawk.Program.<>c__DisplayClass2_0.<SubMain>g__CheckRenderer|2(IGL gl)
   --- End of inner exception stack trace ---
```

In case the underlying cause is Windows 7 compatibility: I cannot downgrade to Windows 10 or 11, for reasons that are beyond the scope of this issue.

**Comment by alyosha-tas** [comment]
I have no way to test or fix windows 7, unfortunately. Could also be a gpu / driver issue.
